spring:
  application:
    name: micro-ms-client
  data:
    mongodb:
      uri: mongodb+srv://momocho20:TVDQKq0W557m8Abn@cluster0.drv6iww.mongodb.net/pybankdb?authSource=pybankdb&authMechanism=SCRAM-SHA-1

logging:
  level:
    org.springframework.data.mongodb: DEBUG

ms-transaccions:
  url: http://localhost:8082/transactions

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
