spring:
  application:
    name: micro-ms-client
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pybankdb
      username: admin
      password: password

logging:
  level:
    org.springframework.data.mongodb: DEBUG

ms-transaccions:
  url: http://localhost:8082/transactions

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
