spring:
  application:
    name: micro-ms-reports
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reports_db

logging:
  level:
    org.springframework.data.mongodb: DEBUG

ms-client:
  url: http://localhost:8080/clients

ms-transaccions:
  url: http://localhost:8082/transactions

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka